### ISSUE TITLE
Error on Generate: Call to private Doctrine\DBAL\Types\Type::__construct() from context 'MigrationsGenerator\DBAL\Schema' 

### ISSUE THREAD

**Issue by marlieer** [kitloong/laravel-migrations-generator#74]
## System
Laravel 8, php 7.3.7, laravel-migrations-generator 5.1, MySQL MariaDB 10.2 image from docker

## Issue Description
Error thrown on `php artisan migrate:generate`
```
php artisan migrate:generate

   Error 

  Call to private Doctrine\DBAL\Types\Type::__construct() from context 'MigrationsGenerator\DBAL\Schema'

  at vendor/kitloong/laravel-migrations-generator/src/MigrationsGenerator/DBAL/Schema.php:220
    216▕      * @throws \Doctrine\DBAL\Exception
    217▕      */
    218▕     protected function registerCustomDoctrineType(string $dbType, string $class): void
    219▕     {
  ➜ 220▕         $doctrineType = (new $class())->getName();
    221▕         if (!Type::hasType($doctrineType)) {
    222▕             Type::addType($doctrineType, $class);
    223▕         } else {
    224▕             Type::overrideType($doctrineType, $class);

      +15 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

## Expected behaviour
Generate migrations for my database

## Stack trace
```
[2022-01-24 20:35:14] local.ERROR: Call to private Doctrine\DBAL\Types\Type::__construct() from context 'MigrationsGenerator\DBAL\Schema' {"exception":"[object] (Error(code: 0): Call to private Doctrine\\DBAL\\Types\\Type::__construct() from context 'MigrationsGenerator\\DBAL\\Schema' at /app/vendor/kitloong/laravel-migrations-generator/src/MigrationsGenerator/DBAL/Schema.php:220)
[stacktrace]
#0 /app/vendor/kitloong/laravel-migrations-generator/src/MigrationsGenerator/DBAL/Schema.php(91): MigrationsGenerator\\DBAL\\Schema->registerCustomDoctrineType('double', 'MigrationsGener...')
#1 /app/vendor/kitloong/laravel-migrations-generator/src/MigrationsGenerator/MigrateGenerateCommand.php(79): MigrationsGenerator\\DBAL\\Schema->initialize()
#2 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): MigrationsGenerator\\MigrateGenerateCommand->handle()
#3 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#5 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#8 /app/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /app/vendor/symfony/console/Application.php(1005): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /app/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(MigrationsGenerator\\MigrateGenerateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /app/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"} 
```

**Comment by kitloong** [comment]
Hi @marlieer 

Thank you for reporting.
I have followed the provided version however I can't reproduce the issue.

```
local.ERROR: Call to private Doctrine\DBAL\Types\Type::__construct()
```
My first guess is the scope of `Doctrine\DBAL\Types\Type::__construct()` is declared as private however after follow the [source code](https://github.com/doctrine/dbal/blob/3.3.x/src/Types/Type.php#L56), I don't think it is the issue.

Could you please provide more info to reproduce?

**Comment by marlieer** [comment]
Thanks for the quick response! I was able to figure it out. My installed Doctrine version (2.9) had the Type construct as private, which you can see on the [source code](https://github.com/doctrine/dbal/blob/ec74d6e300d78fbc896669c3ca57ef9719adc9c6/lib/Doctrine/DBAL/Types/Type.php#L88). There were some other issues raised from using that version of Doctrine, but I've seen been able to use your package. It worked perfectly! Thanks for developing
